apiVersion: v1
kind: Service
metadata:
  name: {{ include "morfeu.fullname" . }}
  labels:
    {{- include "morfeu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8980
      protocol: TCP
      name: http
  selector:
    {{- include "morfeu.selectorLabels" . | nindent 4 }}
